/** Known technology keywords to detect from repo topics, descriptions, and file names */
export const TECH_KEYWORDS: Record<string, string[]> = {
  // Languages
  JavaScript: ['javascript', 'js'],
  TypeScript: ['typescript', 'ts'],
  Python: ['python', 'py'],
  Java: ['java'],
  'C#': ['csharp', 'c-sharp', 'dotnet', '.net'],
  'C++': ['cpp', 'c-plus-plus', 'cplusplus'],
  C: ['c-lang'],
  Go: ['golang', 'go'],
  Rust: ['rust', 'rust-lang'],
  Ruby: ['ruby'],
  PHP: ['php'],
  Swift: ['swift'],
  Kotlin: ['kotlin'],
  Scala: ['scala'],
  R: ['r-lang', 'rstats'],
  Dart: ['dart'],
  Elixir: ['elixir'],
  Haskell: ['haskell'],
  Lua: ['lua'],
  Perl: ['perl'],
  Shell: ['shell', 'bash', 'zsh'],

  // Frontend
  React: ['react', 'reactjs', 'react-js'],
  Vue: ['vue', 'vuejs', 'vue-js'],
  Angular: ['angular', 'angularjs'],
  Svelte: ['svelte', 'sveltekit'],
  'Next.js': ['nextjs', 'next-js', 'next'],
  Nuxt: ['nuxt', 'nuxtjs'],
  Astro: ['astro', 'astrojs'],
  Gatsby: ['gatsby', 'gatsbyjs'],
  'Tailwind CSS': ['tailwindcss', 'tailwind', 'tailwind-css'],
  Bootstrap: ['bootstrap'],
  'Material UI': ['material-ui', 'mui'],
  'Styled Components': ['styled-components'],
  Sass: ['sass', 'scss'],
  Redux: ['redux'],
  Zustand: ['zustand'],
  Vite: ['vite', 'vitejs'],
  Webpack: ['webpack'],

  // Backend
  'Node.js': ['nodejs', 'node', 'node-js'],
  Express: ['express', 'expressjs'],
  Fastify: ['fastify'],
  NestJS: ['nestjs', 'nest-js'],
  Django: ['django'],
  Flask: ['flask'],
  FastAPI: ['fastapi', 'fast-api'],
  'Spring Boot': ['spring-boot', 'spring', 'springboot'],
  'Ruby on Rails': ['rails', 'ruby-on-rails'],
  Laravel: ['laravel'],
  ASP: ['aspnet', 'asp-net', 'asp-net-core'],
  Gin: ['gin', 'gin-gonic'],
  Fiber: ['fiber', 'gofiber'],
  Actix: ['actix', 'actix-web'],

  // Databases
  PostgreSQL: ['postgresql', 'postgres', 'psql'],
  MySQL: ['mysql'],
  MongoDB: ['mongodb', 'mongo'],
  Redis: ['redis'],
  SQLite: ['sqlite'],
  Elasticsearch: ['elasticsearch', 'elastic'],
  Cassandra: ['cassandra'],
  DynamoDB: ['dynamodb'],
  Firebase: ['firebase', 'firestore'],
  Supabase: ['supabase'],
  Prisma: ['prisma'],
  Drizzle: ['drizzle'],

  // DevOps & Cloud
  Docker: ['docker', 'dockerfile', 'docker-compose'],
  Kubernetes: ['kubernetes', 'k8s'],
  AWS: ['aws', 'amazon-web-services'],
  GCP: ['gcp', 'google-cloud'],
  Azure: ['azure', 'microsoft-azure'],
  Terraform: ['terraform', 'hcl'],
  Ansible: ['ansible'],
  'GitHub Actions': ['github-actions'],
  Jenkins: ['jenkins'],
  'CI/CD': ['ci-cd', 'cicd'],
  Nginx: ['nginx'],
  Linux: ['linux'],
  Helm: ['helm'],
  ArgoCD: ['argocd', 'argo-cd'],
  Prometheus: ['prometheus'],
  Grafana: ['grafana'],

  // Mobile
  'React Native': ['react-native', 'reactnative'],
  Flutter: ['flutter'],
  'iOS (SwiftUI)': ['swiftui'],
  Android: ['android'],
  Expo: ['expo'],

  // ML/AI
  TensorFlow: ['tensorflow', 'tf'],
  PyTorch: ['pytorch'],
  'Scikit-learn': ['scikit-learn', 'sklearn'],
  Pandas: ['pandas'],
  NumPy: ['numpy'],
  Jupyter: ['jupyter', 'jupyter-notebook'],
  OpenAI: ['openai', 'gpt', 'chatgpt'],
  LangChain: ['langchain'],
  Hugging_Face: ['huggingface', 'hugging-face', 'transformers'],

  // Testing
  Jest: ['jest'],
  Vitest: ['vitest'],
  Cypress: ['cypress'],
  Playwright: ['playwright'],
  Pytest: ['pytest'],
  Mocha: ['mocha'],
  Storybook: ['storybook'],

  // Tools & Other
  GraphQL: ['graphql', 'gql'],
  REST: ['rest-api', 'restful'],
  gRPC: ['grpc'],
  WebSocket: ['websocket', 'websockets', 'ws'],
  RabbitMQ: ['rabbitmq'],
  Kafka: ['kafka'],
  Git: ['git'],
  Monorepo: ['monorepo', 'turborepo', 'lerna', 'nx'],
  Microservices: ['microservices', 'microservice'],
  OAuth: ['oauth', 'oauth2'],
  JWT: ['jwt', 'json-web-token'],
};

/** Categories for organizing skills */
export const SKILL_CATEGORIES: Record<string, string[]> = {
  Languages: [
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C#',
    'C++',
    'C',
    'Go',
    'Rust',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'Scala',
    'R',
    'Dart',
    'Elixir',
    'Haskell',
    'Lua',
    'Perl',
    'Shell',
  ],
  Frontend: [
    'React',
    'Vue',
    'Angular',
    'Svelte',
    'Next.js',
    'Nuxt',
    'Astro',
    'Gatsby',
    'Tailwind CSS',
    'Bootstrap',
    'Material UI',
    'Styled Components',
    'Sass',
    'Redux',
    'Zustand',
    'Vite',
    'Webpack',
  ],
  Backend: [
    'Node.js',
    'Express',
    'Fastify',
    'NestJS',
    'Django',
    'Flask',
    'FastAPI',
    'Spring Boot',
    'Ruby on Rails',
    'Laravel',
    'ASP',
    'Gin',
    'Fiber',
    'Actix',
  ],
  Databases: [
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'SQLite',
    'Elasticsearch',
    'Cassandra',
    'DynamoDB',
    'Firebase',
    'Supabase',
    'Prisma',
    'Drizzle',
  ],
  'DevOps & Cloud': [
    'Docker',
    'Kubernetes',
    'AWS',
    'GCP',
    'Azure',
    'Terraform',
    'Ansible',
    'GitHub Actions',
    'Jenkins',
    'CI/CD',
    'Nginx',
    'Linux',
    'Helm',
    'ArgoCD',
    'Prometheus',
    'Grafana',
  ],
  Mobile: ['React Native', 'Flutter', 'iOS (SwiftUI)', 'Android', 'Expo'],
  'ML & AI': [
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Jupyter',
    'OpenAI',
    'LangChain',
    'Hugging_Face',
  ],
  Testing: [
    'Jest',
    'Vitest',
    'Cypress',
    'Playwright',
    'Pytest',
    'Mocha',
    'Storybook',
  ],
  'Tools & Infrastructure': [
    'GraphQL',
    'REST',
    'gRPC',
    'WebSocket',
    'RabbitMQ',
    'Kafka',
    'Git',
    'Monorepo',
    'Microservices',
    'OAuth',
    'JWT',
  ],
};
