/** Known technology keywords to detect from repo topics, descriptions, and file names */
export const TECH_KEYWORDS: Record<string, string[]> = {
  // Languages
  JavaScript: ['javascript', 'js'],
  TypeScript: ['typescript', 'ts'],
  Python: ['python', 'py'],
  Java: ['java'],
  // C# and ASP.NET/.NET are one ecosystem — merged into a single skill
  'C# / .NET': [
    'csharp',
    'c-sharp',
    'dotnet',
    '.net',
    'aspnet',
    'asp-net',
    'asp-net-core',
    'blazor',
    'wpf',
  ],
  'C++': ['cpp', 'c-plus-plus', 'cplusplus'],
  C: ['c-lang'],
  Go: ['golang', 'go'],
  Rust: ['rust', 'rust-lang'],
  Ruby: ['ruby'],
  PHP: ['php'],
  Swift: ['swift'],
  Kotlin: ['kotlin'],
  Scala: ['scala'],
  R: ['r-lang', 'rstats'],
  Dart: ['dart'],
  Elixir: ['elixir'],
  Haskell: ['haskell'],
  Lua: ['lua'],
  Perl: ['perl'],
  Shell: ['shell', 'bash', 'zsh', 'shellscript'],

  // Frontend
  React: ['react', 'reactjs', 'react-js'],
  Vue: ['vue', 'vuejs', 'vue-js'],
  Angular: ['angular', 'angularjs'],
  Svelte: ['svelte', 'sveltekit'],
  'Next.js': ['nextjs', 'next-js', 'next'],
  Nuxt: ['nuxt', 'nuxtjs'],
  Astro: ['astro', 'astrojs'],
  Gatsby: ['gatsby', 'gatsbyjs'],
  'Tailwind CSS': ['tailwindcss', 'tailwind', 'tailwind-css'],
  Bootstrap: ['bootstrap'],
  'Material UI': ['material-ui', 'mui'],
  'Styled Components': ['styled-components'],
  HTML: ['html'],
  CSS: ['css'],
  Sass: ['sass', 'scss'],
  Redux: ['redux'],
  Zustand: ['zustand'],
  Vite: ['vite', 'vitejs'],
  Webpack: ['webpack'],

  // Backend
  'Node.js': ['nodejs', 'node', 'node-js'],
  Express: ['express', 'expressjs'],
  Fastify: ['fastify'],
  NestJS: ['nestjs', 'nest-js'],
  Django: ['django'],
  Flask: ['flask'],
  FastAPI: ['fastapi', 'fast-api'],
  'Spring Boot': ['spring-boot', 'spring', 'springboot'],
  'Ruby on Rails': ['rails', 'ruby-on-rails'],
  Laravel: ['laravel'],
  Gin: ['gin', 'gin-gonic'],
  Fiber: ['fiber', 'gofiber'],
  Actix: ['actix', 'actix-web'],

  // Databases
  PostgreSQL: ['postgresql', 'postgres', 'psql'],
  MySQL: ['mysql'],
  MongoDB: ['mongodb', 'mongo'],
  Redis: ['redis'],
  SQLite: ['sqlite'],
  Elasticsearch: ['elasticsearch', 'elastic'],
  Cassandra: ['cassandra'],
  DynamoDB: ['dynamodb'],
  Firebase: ['firebase', 'firestore'],
  Supabase: ['supabase'],
  Prisma: ['prisma'],
  Drizzle: ['drizzle'],

  // DevOps & Cloud
  Docker: ['docker', 'dockerfile', 'docker-compose'],
  // k8s: catch both formal and shorthand naming, plus gitops tools
  Kubernetes: [
    'kubernetes',
    'k8s',
    'kube',
    'kubectl',
    'gitops',
    'kustomize',
    'flux',
  ],
  AWS: ['aws', 'amazon-web-services'],
  GCP: ['gcp', 'google-cloud', 'google-cloud-platform'],
  Azure: ['azure', 'microsoft-azure'],
  Terraform: ['terraform', 'opentofu'],
  Ansible: ['ansible'],
  // GitHub Actions: topic github-actions is common; gha shorthand also used
  'GitHub Actions': ['github-actions', 'github-action', 'gha'],
  Jenkins: ['jenkins'],
  Nginx: ['nginx'],
  Helm: ['helm', 'helmfile'],
  ArgoCD: ['argocd', 'argo-cd', 'argo'],
  Prometheus: ['prometheus'],
  Grafana: ['grafana'],

  // Mobile
  'React Native': ['react-native', 'reactnative'],
  Flutter: ['flutter'],
  SwiftUI: ['swiftui'],
  Android: ['android'],
  Expo: ['expo'],

  // ML/AI
  TensorFlow: ['tensorflow'],
  PyTorch: ['pytorch'],
  'Scikit-learn': ['scikit-learn', 'sklearn'],
  Pandas: ['pandas'],
  NumPy: ['numpy'],
  Jupyter: ['jupyter', 'jupyter-notebook'],
  OpenAI: ['openai', 'gpt', 'chatgpt'],
  LangChain: ['langchain'],
  'Hugging Face': ['huggingface', 'hugging-face', 'transformers'],

  // Testing
  Jest: ['jest'],
  Vitest: ['vitest'],
  Cypress: ['cypress'],
  Playwright: ['playwright'],
  Pytest: ['pytest'],
  Mocha: ['mocha'],
  Storybook: ['storybook'],

  // Tools & Infrastructure
  GraphQL: ['graphql', 'gql'],
  gRPC: ['grpc'],
  WebSocket: ['websocket', 'websockets', 'ws'],
  RabbitMQ: ['rabbitmq'],
  Kafka: ['kafka'],
  Monorepo: ['monorepo', 'turborepo', 'lerna', 'nx'],
  Microservices: ['microservices', 'microservice'],
  OAuth: ['oauth', 'oauth2'],
  JWT: ['jwt', 'json-web-token'],
};

/** Categories for organizing skills */
export const SKILL_CATEGORIES: Record<string, string[]> = {
  Languages: [
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C++',
    'C',
    'Go',
    'Rust',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'Scala',
    'R',
    'Dart',
    'Elixir',
    'Haskell',
    'Lua',
    'Perl',
    'Shell',
  ],
  Frontend: [
    'React',
    'Vue',
    'Angular',
    'Svelte',
    'Next.js',
    'Nuxt',
    'Astro',
    'Gatsby',
    'Tailwind CSS',
    'Bootstrap',
    'Material UI',
    'Styled Components',
    'HTML',
    'CSS',
    'Sass',
    'Redux',
    'Zustand',
    'Vite',
    'Webpack',
  ],
  Backend: [
    'C# / .NET',
    'Node.js',
    'Express',
    'Fastify',
    'NestJS',
    'Django',
    'Flask',
    'FastAPI',
    'Spring Boot',
    'Ruby on Rails',
    'Laravel',
    'Gin',
    'Fiber',
    'Actix',
  ],
  Databases: [
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'SQLite',
    'Elasticsearch',
    'Cassandra',
    'DynamoDB',
    'Firebase',
    'Supabase',
    'Prisma',
    'Drizzle',
  ],
  'DevOps & Cloud': [
    'Docker',
    'Kubernetes',
    'AWS',
    'GCP',
    'Azure',
    'Terraform',
    'Ansible',
    'GitHub Actions',
    'Jenkins',
    'Nginx',
    'Helm',
    'ArgoCD',
    'Prometheus',
    'Grafana',
  ],
  Mobile: ['React Native', 'Flutter', 'SwiftUI', 'Android', 'Expo'],
  'ML & AI': [
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Jupyter',
    'OpenAI',
    'LangChain',
    'Hugging Face',
  ],
  Testing: [
    'Jest',
    'Vitest',
    'Cypress',
    'Playwright',
    'Pytest',
    'Mocha',
    'Storybook',
  ],
  'Tools & Infrastructure': [
    'GraphQL',
    'gRPC',
    'WebSocket',
    'RabbitMQ',
    'Kafka',
    'Monorepo',
    'Microservices',
    'OAuth',
    'JWT',
  ],
};

/** Emoji prefix for skill category headings in UI/Markdown */
export const CATEGORY_EMOJIS: Record<string, string> = {
  Languages: '🧠',
  Frontend: '🎨',
  Backend: '⚙️',
  Databases: '🗄️',
  'DevOps & Cloud': '☁️',
  Mobile: '📱',
  'ML & AI': '🤖',
  Testing: '🧪',
  'Tools & Infrastructure': '🧰',
  Other: '📦',
};
